version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"

  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    environment:
      - VITE_API_URL=http://localhost:3000/api
    ports:
      - "5173:80"
    depends_on:
      - server
