name: bluebubbles
description: Send iMessages on Android using BlueBubbles!
version: 1.15.0+11500
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.6.0
  animated_size_and_fade: ^4.0.0
  animations: ^2.0.11
  archive: ^3.4.13
  app_links: ^6.1.1
  async_task: ^1.1.1
  audio_waveforms: ^1.0.5
  auto_size_text: ^3.0.0
  bitsdojo_window: ^0.1.6
  chunked_stream: ^1.4.2
  collection: ^1.18.0
  confetti: ^0.7.0
  connectivity_plus: ^6.0.2
  crop_your_image: ^1.0.2
  crypto: ^3.0.3
  csslib: ^1.0.0
  cupertino_icons: ^1.0.8
  defer_pointer: ^0.0.3
  desktop_webview_auth: ^0.0.16
  device_info_plus: ^11.0.0
  dio: ^5.5.0+1
  encrypt: ^5.0.3
  equatable: ^2.0.5
  faker: ^2.1.0
  fast_contacts: ^4.0.0
  file_picker: ^8.0.0+1
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_dart:
    git:
      url: https://github.com/appsup-dart/firebase_dart.git
      ref: beb79f70a2bb0e96e6bb9fdebac2ff452f138950
      path: package
  fixnum: ^1.1.0
  fl_chart: ^0.68.0
  flex_color_scheme: ^8.1.1
  flutter_acrylic: ^1.1.4
  flutter_animate: ^4.5.0
  flutter_app_badger: ^1.5.0
  flutter_blurhash: ^0.8.2
  flutter_cache_manager: ^3.3.2
  flutter_displaymode: ^0.6.0
  flutter_fgbg: ^0.3.0
  flutter_foreground_task: ^6.4.3
  flutter_keyboard_visibility: ^6.0.0
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^17.2.2
  flutter_markdown: ^0.7.3
  flutter_osm_plugin: ^0.80.3
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.1.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^2.0.0
  flutter_treeview: ^1.0.7+1
  flutter_vibrate: ^1.3.0
  flutter_web_auth_2: ^4.1.0
  geolocator: ^13.0.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_mlkit_barcode_scanning: ^0.12.0
  google_mlkit_speech_to_text: ^0.12.0
  image: ^4.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  js: ^0.7.1
  lottie: ^3.1.2
  marquee: ^2.3.0
  mime: ^1.0.5
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2
  open_filex: ^4.6.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  path_provider: ^2.1.4
  pdfx: ^2.7.1
  permission_handler: ^11.3.1
  platform_info: ^4.0.2
  pointycastle: ^3.7.3
  qr: ^3.0.2
  qr_flutter: ^4.1.0
  quick_actions: ^1.0.7
  receive_sharing_intent: ^1.8.0
  record: ^5.2.0
  reorderables: ^0.6.0
  rxdart: ^0.28.0
  speech_to_text: ^5.8.0
  screenshot: ^3.0.0
  share_plus: ^10.0.2
  shared_preferences: ^2.3.1
  skeletonizer: ^1.5.0
  sliding_up_panel2: ^3.3.0+1
  sqlite3: ^2.4.5
  system_theme: ^3.1.2
  transparent_image: ^2.0.1
  tray_manager: ^0.2.3
  universal_html: ^2.2.4
  universal_io: ^2.2.2
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  video_compress: ^3.1.3
  video_player: ^2.9.2
  wakelock_plus: ^1.2.8+2
  webview_windows: ^0.4.0
  window_manager: ^0.4.2
  win32_registry: ^1.1.2
  win_toast: ^0.3.0
  xml: ^6.5.0
  workmanager: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: ^4.0.2
  peanut: ^5.1.0
  fake_async: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/emoji/
    - assets/images/
    - assets/sounds/
  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/sf/SF-Pro.ttf

msix_config:
  display_name: BlueBubbles
  publisher_display_name: BlueBubbles
  identity_name: 23344BlueBubbles.BlueBubbles
  msix_version: 1.15.0.0
  publisher: CN=BEC9154D-191E-4375-BF30-698BD4C141C4
  vs_generated_images_folder_path: windows/icons
  logo_path: windows/icons/bluebubbles_logo.png
  certificate_path: windows/BlueBubbles_Temporary.pfx
  certificate_password: bluebubbles
  capabilities: internetClient, location, microphone, webcam
  protocol_activation: imessage
