name: CI (fixed)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Versions
        run: |
          flutter --version
          dart --version

      - name: Pub upgrade & get
        run: |
          flutter pub upgrade --major-versions
          flutter pub get

      - name: Build generated files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Ensure generated files are committed
        run: |
          git status --porcelain
          test -z "$(git status --porcelain)"

      - name: Analyze
        run: flutter analyze

      - name: Run all tests
        run: flutter test
